<a href="https://colab.research.google.com/github/BenMeehan/Foundational_Machine_Learning/blob/main/logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
import pandas as pd
df=pd.read_csv("sn.csv")

In [3]:
y=np.array(df['Purchased'])
y.shape

(400,)

In [4]:
li=[]
for i in df['Gender']:
  if i=="Male":
    li.append(1)
  else:
    li.append(0)

df['Gender']=li

In [5]:
x=np.array(df[['Gender','Age','EstimatedSalary']])
x

array([[    1,    19, 19000],
       [    1,    35, 20000],
       [    0,    26, 43000],
       ...,
       [    0,    50, 20000],
       [    1,    36, 33000],
       [    0,    49, 36000]])

In [6]:
import math
def h(x,m):
  b=[]
  for j in range(len(m)):
      b.append (m[j]*x[j])
  if sum(b) < 0:
      z= 1 - 1/(1 + math.exp(sum(b)))
  else:
      z= 1/(1 + math.exp(-sum(b)))
  return z

In [7]:
def gd(x,y,alpha,iter):
  m=len(x)
  n=len(x[0])

  slope=np.zeros(n)
  slopet=np.zeros(n)

  for _ in range(iter):
    for i in range(m):
      for j in range(n):
        xt=x[i]
        yt=y[i]
        slopet[j]+=(-1/m)*(yt-h(xt,slope))*x[i][j]
    
      slope=slope-(alpha*slopet)
      print(cost(x,y,slope))
  
  return slope 

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
scaler = StandardScaler()
scaler.fit(x[1:])

StandardScaler()

In [10]:
x[1:]=scaler.transform(x[1:])

In [11]:
x[10:20,:]

array([[ 0, -1,  0],
       [ 0, -1,  0],
       [ 1, -1,  0],
       [ 1,  0, -1],
       [ 1, -1,  0],
       [ 1,  0,  0],
       [ 1,  0, -1],
       [ 1,  0, -1],
       [ 1,  0, -1],
       [ 0,  0, -1]])

In [12]:
x=np.c_[x,np.ones(len(x))]

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y)

In [24]:
m=gd(xtrain,ytrain,0.0001,50)

Streaming output truncated to the last 5000 lines.
0.4548604055068418
0.4548585997329455
0.4548568044943809
0.45485501887855684
0.45485322754720703
0.45485146739040755
0.4548497168447194
0.45484793039112137
0.4548461313653267
0.45484430288719646
0.45484246869506983
0.45484061995786235
0.45483876713915067
0.45483692392319525
0.45483508704500586
0.4548332547150498
0.4548314328923353
0.4548295928225012
0.45482776325207114
0.454825934225469
0.4548241147876482
0.4548222998471899
0.45482049540029884
0.4548186860772106
0.4548168586555291
0.45481502636449767
0.454813175982971
0.4548113207757578
0.45480947515640807
0.4548076350787594
0.45480577691849894
0.4548039235438836
0.4548020806606069
0.4548002473610594
0.45479842364366785
0.45479661041243097
0.4547947791093867
0.45479293521559017
0.4547911018064497
0.45478925394986164
0.45478741567214515
0.4547855878763084
0.45478375523631714
0.45478193307739645
0.454780074884442
0.4547782229960991
0.4547763815794743
0.4547745275596029
0.4547726798402295

In [25]:
xtest.shape

(100, 4)

In [32]:
pred_y=[]
def predict(x,y,m):
  count=0
  res=0
  for i in range(len(x)):
    t=h(x[i],m)
    if t>0.5:
      res=1 
    else:
      res=0
    if res==y[i]:
      count+=1 
    pred_y.append(res)
  print(count)

In [33]:
predict(xtest,ytest,m)

80


In [28]:
m

array([-0.39835747,  3.96054147,  2.15780398, -1.36353433])

In [16]:
def cost(x,y,m):
  s=0
  for i in range(len(x)):
    xt=x[i]
    yt=y[i]
    t=h(xt,m)
    if t==0:
      s+=(1-yt)*math.log(1-t)
    elif t==1:
      s+=yt*math.log(t)
    else:
      s+=yt*math.log(t)+(1-yt)*math.log(1-t)
  s=(-1/len(x))*s
  return s

In [29]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0).fit(xtrain, ytrain)

In [30]:
clf.score(xtest,ytest)

0.8

In [31]:
from sklearn.metrics import confusion_matrix

In [35]:
confusion_matrix(ytest,pred_y)

array([[57,  5],
       [15, 23]])

In [36]:
ypr=clf.predict(xtest)

In [38]:
confusion_matrix(ytest,ypr)

array([[57,  5],
       [15, 23]])

In [39]:
from sklearn.metrics import classification_report

In [40]:
print(classification_report(ytest, pred_y))

              precision    recall  f1-score   support

           0       0.79      0.92      0.85        62
           1       0.82      0.61      0.70        38

    accuracy                           0.80       100
   macro avg       0.81      0.76      0.77       100
weighted avg       0.80      0.80      0.79       100

